// Materialises the pinned @deepseek-ai/* host packages (ci/pinned-deps.json)
// in a clean checkout WITHOUT touching this package.json's dependency surface
// (optional peers must stay optional; the maintainer machine's node_modules
// is a junction into a dsh profile and must not be reified by npm).
//
// Mechanism: a generated standalone npm project under ci/deps/ installs the
// pinned set (npm ci against the committed ci/deps/package-lock.json when it
// matches, npm install otherwise), then the ci/deps/node_modules/@deepseek-ai
// scope directory is linked into the repo root's node_modules so the test
// buckets' bare specifiers resolve. If the root already has a real (non-link)
// @deepseek-ai tree — maintainer junction machine, or a prior full install —
// the link step is skipped and only the presence of each pinned package is
// verified. Same command locally and in CI: `node ci/install-pinned.mjs`.
import { spawnSync } from 'node:child_process'
import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

const here = path.dirname(fileURLToPath(import.meta.url))
const root = path.join(here, '..')
const depsDir = path.join(here, 'deps')
const { deps } = JSON.parse(readFileSync(path.join(here, 'pinned-deps.json'), 'utf8'))

// Same npm-spawning pattern as scripts/verify-install.mjs: on win32 a bare
// spawn of npm.cmd throws EINVAL on Node >= 24, and npm_execpath is not set
// outside npm lifecycle.
function runNpm(args, cwd) {
  const execpath = process.env.npm_execpath
  if (execpath !== undefined && execpath.endsWith('.js')) {
    return spawnSync(process.execPath, [execpath, ...args], { cwd, stdio: 'inherit' }).status ?? 1
  }
  const program = process.platform === 'win32' ? 'npm.cmd' : 'npm'
  return spawnSync(program, args, { cwd, stdio: 'inherit', shell: process.platform === 'win32' }).status ?? 1
}

mkdirSync(depsDir, { recursive: true })
const generated = {
  name: 'dsh-wsl-workspace-ci-deps',
  private: true,
  description: 'Generated by ci/install-pinned.mjs from ci/pinned-deps.json — edit the pin file, not this manifest.',
  dependencies: deps,
}
const manifestPath = path.join(depsDir, 'package.json')
const current = existsSync(manifestPath) ? JSON.parse(readFileSync(manifestPath, 'utf8')) : null
if (!current || JSON.stringify(current.dependencies) !== JSON.stringify(generated.dependencies)) {
  writeFileSync(manifestPath, JSON.stringify(generated, null, 2) + '\n')
}
writeFileSync(path.join(depsDir, '.npmrc'), 'legacy-peer-deps=true\n')

const lockPath = path.join(depsDir, 'package-lock.json')
let status
if (existsSync(lockPath)) {
  status = runNpm(['ci', '--no-audit', '--no-fund'], depsDir)
  if (status !== 0) {
    console.log('install-pinned: npm ci out of sync with pins — falling back to npm install (if pins changed, commit the refreshed ci/deps/package-lock.json)')
    status = runNpm(['install', '--no-audit', '--no-fund'], depsDir)
  }
} else {
  status = runNpm(['install', '--no-audit', '--no-fund'], depsDir)
}
if (status !== 0) {
  console.error(`install-pinned: dependency install in ${depsDir} failed with exit status ${status}`)
  process.exit(1)
}

const depsModules = path.join(depsDir, 'node_modules')
// Link the @deepseek-ai scope and the listed unscoped bare imports (pin file
// 'unscoped' — e.g. js-yaml, which src/index.ts dynamic-imports) from
// ci/deps/node_modules into the root; nothing else, so transitive bloat never
// multiplies links. Existing root entries — including the maintainer's
// junction — are never touched.
const { unscoped } = JSON.parse(readFileSync(path.join(here, 'pinned-deps.json'), 'utf8'))
const linkOne = (src, dst) => (process.platform === 'win32'
  ? spawnSync('cmd', ['/c', 'mklink', '/J', dst, src], { stdio: 'ignore', shell: false }).status ?? 1
  : spawnSync('ln', ['-s', src, dst], { stdio: 'ignore' }).status ?? 1)
mkdirSync(path.join(root, 'node_modules'), { recursive: true })
let linked = 0
function linkOrSkip(src, dst) {
  if (existsSync(dst)) return
  if (linkOne(src, dst) !== 0) {
    console.error(`install-pinned: linking ${src} -> ${dst} failed`)
    process.exit(1)
  }
  linked++
}
const scopeSrc = path.join(depsModules, '@deepseek-ai')
const scopeDst = path.join(root, 'node_modules', '@deepseek-ai')
// Always per-package (an existing scope dir may still be missing individual
// names); on the maintainer junction machine every existsSync below is true
// through the junction, so nothing is created.
mkdirSync(scopeDst, { recursive: true })
for (const name of Object.keys(deps)) {
  if (!name.startsWith('@deepseek-ai/')) continue
  const short = name.slice('@deepseek-ai/'.length)
  linkOrSkip(path.join(scopeSrc, short), path.join(scopeDst, short))
}
for (const name of unscoped ?? []) linkOrSkip(path.join(depsModules, name), path.join(root, 'node_modules', name))
console.log(`install-pinned: linked ${linked} package(s) from ci/deps into the root node_modules`)

let failed = false
const rows = []
for (const [name, pinned] of Object.entries(deps)) {
  let actual = 'MISSING'
  for (const base of [path.join(depsDir, 'node_modules'), path.join(root, 'node_modules')]) {
    const manifest = path.join(base, ...name.split('/'), 'package.json')
    if (existsSync(manifest)) {
      actual = JSON.parse(readFileSync(manifest, 'utf8')).version
      break
    }
  }
  if (actual === 'MISSING') failed = true
  rows.push(`pinned: ${name}@${pinned} -> ${actual}`)
}
console.log(rows.join('\n'))
if (failed) {
  console.error('install-pinned: FAILED — a pinned package did not materialise')
  process.exit(1)
}
console.log('install-pinned: OK')
